id: PFC25BD29
initial_creation_type: ocr
source_metadata:
  volumes:
    ec45ed50bd744e8e8b3b92ce5f85cc86:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རྡོ་རྗེ་རྣལ་འབྱོར་མ་ལ་བསྟོད་པ།
      total_pages: 1544
      volume_number: 12
